spring.datasource.url=jdbc:postgresql://localhost:5432/tcc_db
spring.datasource.username=tcc_user
spring.datasource.password=tcc_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.crypto.secret=9s8d7f6a5s4d3f2g