-- Initial schema for Talkie (generated from Hibernate schema export at commit 87916ea)
-- This represents the baseline state before the 'status' column was added to occurrences
-- V2 and V3 add the 'status' column and evolve the enum values

CREATE TABLE public.users (
    id uuid NOT NULL,
    cpf character varying(255),
    email character varying(255),
    name character varying(255),
    password character varying(255),
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE public.types (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    icon character varying(255),
    name character varying(255)
);

CREATE TABLE public.subcategories (
    category_id bigint NOT NULL,
    id bigint NOT NULL,
    name character varying(255)
);

CREATE TABLE public.occurrences (
    category_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    subcategory_id bigint NOT NULL,
    owner_id uuid NOT NULL,
    description text,
    location character varying(255),
    title character varying(255)
);

CREATE TABLE public.subscriptions (
    category_id bigint,
    id bigint NOT NULL,
    subscribed_at timestamp(6) without time zone,
    subscriber_id uuid
);

-- Sequences
ALTER TABLE public.occurrences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.occurrences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.subcategories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subcategories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary Keys
ALTER TABLE ONLY public.occurrences ADD CONSTRAINT occurrences_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subcategories ADD CONSTRAINT subcategories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subscriptions ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.types ADD CONSTRAINT types_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Unique Constraints
ALTER TABLE ONLY public.subscriptions ADD CONSTRAINT subscriptions_subscriber_id_category_id_key UNIQUE (subscriber_id, category_id);
ALTER TABLE ONLY public.types ADD CONSTRAINT types_name_key UNIQUE (name);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_cpf_key UNIQUE (cpf);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_email_key UNIQUE (email);

-- Foreign Keys
ALTER TABLE ONLY public.occurrences ADD CONSTRAINT fkio642d3h0kqkjrawf8copc10s FOREIGN KEY (subcategory_id) REFERENCES public.subcategories(id);
ALTER TABLE ONLY public.occurrences ADD CONSTRAINT fkkfmuuyc85rabkrumgo0c6q5d1 FOREIGN KEY (category_id) REFERENCES public.types(id);
ALTER TABLE ONLY public.occurrences ADD CONSTRAINT fkm0l5p8ar9jv2lat213qua8fj3 FOREIGN KEY (owner_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.subcategories ADD CONSTRAINT fk73pjobmfgddilpae879y7u3f2 FOREIGN KEY (category_id) REFERENCES public.types(id);
ALTER TABLE ONLY public.subscriptions ADD CONSTRAINT fk281qomw8ih4cg24ol6yyeammg FOREIGN KEY (category_id) REFERENCES public.types(id);
ALTER TABLE ONLY public.subscriptions ADD CONSTRAINT fkoodc4352epkjrvxx79odlxbji FOREIGN KEY (subscriber_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.types ADD CONSTRAINT fke9jhleoesq8lrvbefjx4o7hh FOREIGN KEY (user_id) REFERENCES public.users(id);
