import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Button from '@/components/ui/Button';
import Badge from '@/components/ui/Badge';
import { Search, Plus } from 'lucide-react';
export function OccurrencesTable({ occurrences, isLoading }) {
    const navigate = useNavigate();
    const [searchTerm, setSearchTerm] = useState('');
    const filtered = occurrences.filter((occ) => occ.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        occ.categoryName.toLowerCase().includes(searchTerm.toLowerCase()));
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex gap-4 items-center", children: [_jsxs("div", { className: "flex-1 relative", children: [_jsx("div", { className: "absolute left-4 top-1/2 -translate-y-1/2", children: _jsx(Search, { size: 18, className: "text-brand-muted" }) }), _jsx("input", { type: "text", placeholder: "Pesquisar", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full pl-10 pr-4 py-3 border border-black-100 rounded-2xl text-sm placeholder-brand-muted focus:outline-none focus:ring-2 focus:ring-brand-blue focus:ring-opacity-50" })] }), _jsxs(Button, { variant: "dashboard", onClick: () => navigate('/ocorrencias/nova'), className: "flex items-center gap-2", children: [_jsx(Plus, { size: 18 }), _jsx("span", { className: "hidden sm:inline", children: "Nova Ocorr\u00EAncia" })] })] }), _jsx("div", { className: "bg-white rounded-lg overflow-hidden shadow-sm", children: isLoading ? (_jsxs("div", { className: "p-8 text-center", children: [_jsx("div", { className: "inline-block h-8 w-8 animate-spin rounded-full border-4 border-brand-blue border-t-transparent" }), _jsx("p", { className: "mt-2 text-black-500", children: "Carregando..." })] })) : filtered.length === 0 ? (_jsx("div", { className: "p-8 text-center", children: _jsx("p", { className: "text-black-500", children: "Nenhuma ocorr\u00EAncia encontrada" }) })) : (_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-black-100 bg-black-50", children: [_jsx("th", { className: "px-6 py-4 text-left font-medium text-black-700", children: "T\u00EDtulo da Ocorr\u00EAncia" }), _jsx("th", { className: "px-6 py-4 text-left font-medium text-black-700", children: "Categoria" }), _jsx("th", { className: "px-6 py-4 text-left font-medium text-black-700", children: "Subcategoria" }), _jsx("th", { className: "px-6 py-4 text-left font-medium text-black-700", children: "Status" })] }) }), _jsx("tbody", { children: filtered.map((occurrence, idx) => (_jsxs("tr", { className: "border-b border-black-100 hover:bg-black-50", children: [_jsx("td", { className: "px-6 py-4 text-black-900 font-medium", children: occurrence.title }), _jsx("td", { className: "px-6 py-4 text-black-500", children: occurrence.categoryName }), _jsx("td", { className: "px-6 py-4 text-black-500", children: occurrence.subcategoryName }), _jsx("td", { className: "px-6 py-4", children: _jsx(Badge, { status: occurrence.status }) })] }, idx))) })] }) })) })] }));
}
//# sourceMappingURL=OccurrencesTable.js.map